version: "3"
services:
  manejador:
    build: ./manejador
    ports:
      - "8080:8080"
    networks:
      - subasta-net

  postores:
    build: ./postores
    ports:
      - "8081:8081"
    networks:
      - subasta-net
    depends_on:
      - manejador

networks:
  subasta-net:
    driver: bridge
